In [45]:
import torch
device = torch.device(
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
print(f"Using device: {device}")

Using device: mps


In [46]:
x = torch.randn(10, 10)
x = x.to(device)
print(x)


tensor([[ 0.0367, -0.4888, -0.9928,  0.4129,  1.2624, -0.2340,  1.7939, -1.9676,
         -0.0631, -0.2459],
        [-0.3992, -0.5212, -0.5598,  1.7087, -1.2513, -1.1412, -2.1924, -0.7667,
          0.0078,  0.4022],
        [ 0.7641, -0.1307, -0.3280,  0.7835, -0.4810, -1.1071, -0.1854,  0.2910,
         -1.4887,  0.5380],
        [-0.4866,  0.8470,  1.0857, -0.6303,  0.7447, -0.0407,  1.0940,  1.2137,
          0.5198,  1.1161],
        [ 0.8069,  0.5096, -0.3517,  0.7275, -0.9309, -0.8844, -1.4490, -3.0232,
         -0.0778, -0.9508],
        [ 0.0531,  0.2062, -1.3505, -0.3840, -2.1324,  0.5003, -0.2475, -1.5130,
         -0.4096,  1.3668],
        [ 1.5024, -0.3849, -1.4765, -1.3029,  1.0688, -1.2851,  0.2351, -1.3615,
         -0.1067, -1.1537],
        [-1.8080,  0.0667, -1.1386,  0.3278,  0.1519, -1.1049,  0.2925,  0.9918,
          0.4553, -0.8677],
        [-0.1025,  0.0622,  0.1307,  0.2855, -0.7171,  0.8480, -0.8056,  1.4030,
          1.7593,  1.4915],
        [-1.1211,  

In [47]:
print(device)

mps


In [48]:
y = torch.randn(2,3)
y = y.to(device)

In [52]:
z = torch.zeros(2,3)
z = z.to(device)


In [50]:

print(z.device)

cpu


In [53]:
print(y.device)
print(z.device)

mps:0
mps:0


In [55]:
k = z+y
print(k)

tensor([[ 0.2368,  0.2837,  0.4328],
        [ 0.4465, -1.4866, -0.3106]], device='mps:0')


In [56]:
k = z @ y.T
print(k)



tensor([[0., 0.],
        [0., 0.]], device='mps:0')


In [57]:
k.device

device(type='mps', index=0)

In [59]:
print(y)

tensor([[ 0.2368,  0.2837,  0.4328],
        [ 0.4465, -1.4866, -0.3106]], device='mps:0')


In [58]:
k = y.sum(dim=1)
print(k)

k = y.sum(dim=0)
print(k)

tensor([ 0.9533, -1.3507], device='mps:0')
tensor([ 0.6833, -1.2028,  0.1222], device='mps:0')
